# Generated by Django 6.1 on 2026-08-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customerprofile_purchase_purchaseitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
