# Generated by Django 6.1 on 2026-08-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_customerprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='delivery_address',
        ),
    ]
