# Generated by Django 6.1 on 2026-08-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_purchase_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
    ]
